[tool.poetry]
name = "tidal-async"
version = "0.1.0"
description = "Python Tidal streaming service unofficial API in async fashion supporting OAuth2 authentication"
authors = ["JuniorJPDJ <dev@juniorjpdj.pl>"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6"
androguard = {version = "^3.3.5", optional = true}
http-seekable-file = {git = "https://github.com/JuniorJPDJ/http-seekable-file", extras = ["async"], optional = true}

[tool.poetry.extras]
client_id = ["androguard"]
filelike = ["http-seekable-file"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
