name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    name: Linters
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0
